---
version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  console:
    format: '%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter : console
  bugzilla_fl:
    class: logging.FileHandler
    filename: '/tmp/bugzilla_metric.log'
    level: DEBUG
    formatter: default
loggers:
  dumper:
    level: INFO
    handlers: [console]
    propagate: False
  trackers:
    level: INFO
    handlers: [console, bugzilla_fl]
    propagate: False
root:
  level: INFO
  handlers: [console]
  #formatter : default
